import PDFDocument from 'pdfkit';


export interface ICreateInvoicePayload {
    invoiceId: string
    patientName: string
    patientEmail: string
    doctorName: string
    doctorEmail: string
    scheduleDate: string
    amount: string
    transactionId: string
    status: string
    paymentDate: string
}

export const generateInvoice = async (
    payload: ICreateInvoicePayload
): Promise<Buffer> => {

    return new Promise((resolve, reject) => {


        try {

            const doc = new PDFDocument({
                size: "A4",
                margin: 50
            })

            const chunks: Buffer[] = []

            doc.on("data", (chunk) => chunks.push(chunk))

            doc.on("end", () => {
                resolve(Buffer.concat(chunks))
            })

            doc.on("error", (error) => {
                reject(error)
            })

            /* ---------------- Header ---------------- */

            doc
                .fontSize(22)
                .text("MEDICAL APPOINTMENT INVOICE", {
                    align: "center"
                })

            doc.moveDown()

            doc
                .fontSize(10)
                .text(`Invoice ID: ${payload.invoiceId}`)
                .text(`Transaction ID: ${payload.transactionId}`)
                .text(`Status: ${payload.status}`)
                .text(`Payment Date: ${new Date(payload.paymentDate).toLocaleDateString()}`)

            doc.moveDown(2)

            /* ---------------- Patient Info ---------------- */

            doc
                .fontSize(14)
                .text("Patient Information", {
                    underline: true
                })

            doc
                .fontSize(11)
                .text(`Name: ${payload.patientName}`)
                .text(`Email: ${payload.patientEmail}`)

            doc.moveDown()

            /* ---------------- Doctor Info ---------------- */

            doc
                .fontSize(14)
                .text("Doctor Information", {
                    underline: true
                })

            doc
                .fontSize(11)
                .text(`Name: ${payload.doctorName}`)
                .text(`Email: ${payload.doctorEmail}`)

            doc.moveDown()

            /* ---------------- Appointment Info ---------------- */

            doc
                .fontSize(14)
                .text("Appointment Details", {
                    underline: true
                })

            doc
                .fontSize(11)
                .text(`Appointment Date: ${new Date(payload.scheduleDate).toLocaleString()}`)

            doc.moveDown(2)

            /* ---------------- Invoice Table ---------------- */

            doc
                .fontSize(14)
                .text("Payment Summary", {
                    underline: true
                })

            doc.moveDown()

            const tableTop = doc.y

            doc
                .fontSize(11)
                .text("Description", 50, tableTop)
                .text("Amount", 400, tableTop)

            doc.moveDown()

            const itemY = tableTop + 25

            doc
                .text("Doctor Appointment Fee", 50, itemY)
                .text(`৳ ${payload.amount}`, 400, itemY)

            doc.moveDown(3)

            /* ---------------- Total ---------------- */

            doc
                .fontSize(16)
                .text(`Total Paid: ৳ ${payload.amount}`, {
                    align: "right"
                })

            doc.moveDown(3)

            /* ---------------- Footer ---------------- */

            doc
                .fontSize(10)
                .text(
                    "Thank you for using our healthcare appointment system.",
                    { align: "center" }
                )

            doc
                .text(
                    "This invoice was automatically generated by the system.",
                    { align: "center" }
                )

            doc.end()
        } catch (error) {
            console.log(error);

            reject(error)
        }
    })
}